### ISSUE TITLE
Merging

### ISSUE THREAD

**Issue by karljfrisch** [yr23/Chess#1]
We're probably gonna have to figure out a better system or learn how to merge with Github.  And I don't want to learn things

**Comment by karljfrisch** [comment]
Anyway the build is currently broken.  I think it has something to do with the move history widget and the move history ui elements colliding.

**Comment by yr23** [comment]
I fixed some stuff and commited and my build works now. It looks like some of your changes overrode the ones that I made. ALso the old UI got layered with the new one for some reason. Let me know if there are more issues.

**Comment by yr23** [comment]
So it appears this is what happened:

Scene: Slack on Friday Morning

Karl: Hey, you can delete all UI elements for move history.
Me: Okay cool. WIll do that TONIGHT.
Karl: sounds good.

Scene: Github on Friday Night

Me: Delete UI elements and write new implementation of move history
Karl: Delete UI elements as well and resize old move history on UI

Me: commit. build ok
Karl: commit. break build. override changes.

Haha. This one is not too bad though. we could set up separate times to work on things or handle merges as they happen. Up to you.

**Comment by karljfrisch** [comment]
Did you commit your fix to the build?  I don't see it in github desktop or the web.

Hey that slack chat looks familiar.  If you just shifted words around, added some and changed their entire meaning you'd have one of our conversations.

I think SVN has spoiled me.  I much prefer settling conflicts locally before committing.

I think next time I'll just save a copy locally, pull down the changed files and put my changes back in.  OR just never commit again

**Comment by yr23** [comment]
My bad. I commited but forgot to sync. Should be fine now and the stuff I am working on in the near future shouldnt cause merge conflicts.

**Comment by yr23** [comment]
Ok. So I added an  update to undo-move. I didn't ensure the stability of the flags you set for en-passant and castling. Can you take a look at that?

Also, it seems like your functionality for the border for possible moves has dissapeared for me? DO you still have it?

**Comment by karljfrisch** [comment]
I can't check until tomorrow. I'll put it back in if it's gone and hopefully get to putting in check. Undo move might require some tracking of when castling flags get toggled.  Thanks for fixing the build
